version: '3.8'

services:

  postgres:
    image: postgres:18-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.9.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"


  user-service:
    build: { context: ., dockerfile: user-service/Dockerfile }
    container_name: user-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on: [postgres, kafka, discovery-service, config-server]

  notification-service:
    build: { context: ., dockerfile: notification-service/Dockerfile }
    container_name: notification-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on: [kafka, mailhog, discovery-service, config-server]



  config-server:
    build: { context: ., dockerfile: config-server/Dockerfile }
    container_name: config-server
    ports: ["8888:8888"]
    volumes:
      - ./config-server/src/main/resources/config-repo:/config-repo

  discovery-service:
    build: { context: ., dockerfile: discovery-service/Dockerfile }
    container_name: discovery-service
    ports: ["8761:8761"]

  gateway-service:
    build: { context: ., dockerfile: gateway-service/Dockerfile }
    container_name: gateway-service
    ports: ["8080:8080"]
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on: [discovery-service, config-server]



volumes:
  pgdata: